In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
arr = np.array([1, 2, 3, 4], np.int8)

In [5]:
print(arr)

[1 2 3 4]


In [6]:
arr.dtype

dtype('int8')

In [7]:
zeros = np.zeros((2, 5))

In [8]:
zeros.size

10

In [9]:
rng = np.arange(15)

In [10]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
lspace = np.linspace(1, 50, 4)  # Beginning 1, ending 50, equally spaced numbers = 4

In [12]:
lspace

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

In [13]:
emp = np.empty((10, 10))

In [14]:
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        6.95288336e-310, 4.74303020e-322, 9.86834655e-312,
        9.86834655e-312, 9.86834655e-312, 9.86834654e-312,
        9.86834655e-312],
       [9.86837269e-312, 9.86834652e-312, 9.86834651e-312,
        9.86834659e-312, 9.86948285e-312, 9.86949861e-312,
        9.86949861e-312, 9.86837536e-312, 9.86948328e-312,
        9.86948334e-312],
       [9.86948335e-312, 9.86948328e-312, 9.86948328e-312,
        9.86949861e-312, 9.86949862e-312, 9.86948328e-312,
        9.86949862e-312, 9.86949909e-312, 9.86949862e-312,
        9.86949862e-312],
       [9.86948328e-312, 9.86944155e-312, 9.86948284e-312,
        9.86834747e-312, 9.86859190e-312, 9.86948329e-312,
        9.86948328e-312, 9.86949910e-312, 9.86949863e-312,
        9.86949863e-312],
       [9.86948328e-312, 9.86839947e-312, 9.86949863e-312,
        9.86948336e-312, 9.86949910e-312, 9.86834952e-312,
        9.86949864e-312, 9.86949911e-312, 9.86944155e-312,
        9.8

In [15]:
emp_like = np.empty_like(lspace)

In [16]:
emp_like

array([ 1.        , 17.33333333, 33.66666667, 50.        ])

In [17]:
id = np.identity(20, np.int8)

In [18]:
id

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

In [19]:
arr = np.arange(99)

In [20]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [21]:
arr.reshape(33, 3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [22]:
arr.reshape(11, 9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50, 51, 52, 53],
       [54, 55, 56, 57, 58, 59, 60, 61, 62],
       [63, 64, 65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78, 79, 80],
       [81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [23]:
x = [[1, 2, 3], [4, 5, 6], [7, 1, 0]]

In [24]:
arr = np.array(x, np.int8)

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]], dtype=int8)

In [26]:
arr.sum(axis=0)

array([12,  8,  9])

In [27]:
arr.sum(axis=1)

array([ 6, 15,  8])

In [28]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]], dtype=int8)

In [29]:
arr.flat

In [30]:
for item in arr.flat:
    print(item, end=" ")

1 2 3 4 5 6 7 1 0 

In [31]:
arr.ndim

2

In [32]:
arr.size

9

In [33]:
arr.nbytes

9

In [34]:
one = np.array([1, 2, 45, -69, 3211, 98, 3], np.int8)

In [35]:
one.argmax()

5

In [36]:
one.argmin()

4

In [37]:
one.argsort()

array([4, 3, 0, 1, 6, 2, 5], dtype=int64)

In [38]:
two = np.array([1, 2, 3, 4], np.int8)

In [39]:
two

array([1, 2, 3, 4], dtype=int8)

In [40]:
arr.argmax()

6

In [41]:
arr.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [42]:
arr.argmin(axis=1)

array([0, 0, 2], dtype=int64)

In [43]:
arr.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [44]:
arr.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [51]:
arr2 = np.array([[4, 2, 3], [0, 1, 3], [3, 0, 10]])
print(arr, arr2, sep="\n")

[[1 2 3]
 [4 5 6]
 [7 1 0]]
[[ 4  2  3]
 [ 0  1  3]
 [ 3  0 10]]


In [52]:
arr + arr2

array([[ 5,  4,  6],
       [ 4,  6,  9],
       [10,  1, 10]])

In [53]:
arr * arr2

array([[ 4,  4,  9],
       [ 0,  5, 18],
       [21,  0,  0]])

In [54]:
arr2

array([[ 4,  2,  3],
       [ 0,  1,  3],
       [ 3,  0, 10]])

In [56]:
np.where(arr2 > 5)

(array([2], dtype=int64), array([2], dtype=int64))